"""UR5 EV battery disassembly main program.

Initialises the vision system once on startup, then runs a production
loop until the operator shuts down.

Files required in the same folder:
    calibration_params.json  — generated by ur5_calibration.py
    homography.npy           — generated on first homography setup
"""
import time
import sys
sys.path.append(r"C:\RoboDK\Python")

import cv2

from ur5_vision import CAMERA_CONFIG, Camera, Detector, Homography, load_params
from ur5_ui import ask_operator, run_homography_setup, save_detection_image, show_detection

import robodk.robolink as rl
from robodk.robolink import RUNMODE_SIMULATE
from robodk.robolink import RUNMODE_RUN_ROBOT
import robotMovement as rm

RDK = rl.Robolink()
RDK.setRunMode(RUNMODE_SIMULATE)
RDK.setRunMode(RUNMODE_RUN_ROBOT)
robot = RDK.Item("UR5", rl.ITEM_TYPE_ROBOT)

rm.init(RDK, robot)

def main() -> None:
    """Runs the UR5 battery disassembly production loop."""
    print('--- UR5 Battery Disassembly System ---')

    # Load calibration parameters from file.
    # To run a fresh calibration on startup, remove the # from the line below.
    # from ur5_calibration import Calibration; Calibration(camera).run()

    load_params()

    # To use a static image instead of a live camera, replace the next line with:
    # camera = Camera.from_image('snapshot.jpg')  # jpg/png/bmp, same folder as this file.
    camera = Camera.from_device(CAMERA_CONFIG['index'], CAMERA_CONFIG['buffer_size'])

    homography = Homography()
    run_homography_setup(camera, homography)
    detector = Detector(camera, homography)

    if not ask_operator('Start battery disassembly?'):
        camera.release()
        cv2.destroyAllWindows()
        return

    while True:
        
        robot.setSpeed(100, 60, 500, 40)  # linear speed, joint speed, linear accel, joint accel
        rm.moveToPlace("above_lid_dump", useTarget=True) #above_lid_dump, is also the homeposition

        rm.moveToPlace("above_lid", useTarget=True)

        rm.pickOrPlace(
        above="above_lid",
        on="on_lid",
        gripper="close",
        useTarget=True
        )

        rm.moveToPlace("above_lid_dump", useTarget=True)

        rm.pickOrPlace(
            above="above_lid_dump",
            on="on_lid_dump",
            gripper="open",
            useTarget=True
        )

        time.sleep(2.5)

        frame = camera.get_cropped_frame()
        result = detector.detect()
        print(f'\nDetected {len(result.positions)} module(s).')
        print(f'positions: {result.positions}')
        print(f'is_red:    {result.is_red}')

        show_detection(frame, result)

        # To save the detection result image, remove the # from the line below.
        # save_detection_image(frame, result)
        robot.setSpeed(400, 240, 2000, 160)  # linear speed, joint speed, linear accel, joint accel

        Modules = []
        for is_red, positions in zip(result.is_red,result.positions):
            Modules.append({
                "red":is_red,
                "x": positions[0],
                "y": positions[1],
                "z": 5 # Uden fingre skal der stå 26 her, og hvis man tilføjer fingre skal man trække højden af dem fra her.
            })
            
        dumpTæller = 1
        for Position in Modules:
            if Position["red"]:

                rm.moveToPlace(
                    x=Position["x"],
                    y=Position["y"],
                    z=Position["z"],
                    useTarget=False
                )

                rm.pickOrPlace(
                    x=Position["x"],
                    y=Position["y"],
                    z=Position["z"],
                    gripper="close",
                    useTarget=False
                )

                rm.moveToPlace(f"modul_dump_{dumpTæller}_above", useTarget=True)

                rm.pickOrPlace(
                    above=f"modul_dump_{dumpTæller}_above",
                    on=f"modul_dump_{dumpTæller}_on",
                    gripper="open",
                    useTarget=True
                )

                dumpTæller += 1

        rm.moveToPlace("above_lid_dump", useTarget=True)


        if not ask_operator('Run again with next battery?'):
            break

    camera.release()
    cv2.destroyAllWindows()
    print('--- System shut down ---')


if __name__ == '__main__':
    main()