"""UR5 EV battery disassembly main program.

Initialises the vision system once on startup, then runs a production
loop until the operator shuts down.

Files required in the same folder:
    calibration_params.json  — generated by ur5_calibration.py
    homography.npy           — generated on first homography setup
"""

import cv2

from ur5_vision import CAMERA_CONFIG, Camera, Detector, Homography, load_params
from ur5_ui import ask_operator, run_homography_setup, save_detection_image, show_detection


def main() -> None:
    """Runs the UR5 battery disassembly production loop."""
    print('--- UR5 Battery Disassembly System ---')

    # Load calibration parameters from file.
    # To run a fresh calibration on startup, remove the # from the line below.
    # from ur5_calibration import Calibration; Calibration(camera).run()
    load_params()

    # Initialise camera.
    # To use a static image instead of a live camera, replace the next line with:
    # camera = Camera.from_image('snapshot.jpg')  # jpg/png/bmp, same folder as this file.
    camera = Camera.from_device(CAMERA_CONFIG['index'], CAMERA_CONFIG['buffer_size'])

    homography = Homography()
    run_homography_setup(camera, homography)
    detector = Detector(camera, homography)

    if not ask_operator('Start battery disassembly?'):
        camera.release()
        cv2.destroyAllWindows()
        return

    while True:
        # Robot: remove lid here.

        frame = camera.get_cropped_frame()
        result = detector.detect()
        print(f'\nDetected {len(result.positions)} module(s).')
        print(f'positions: {result.positions}')
        print(f'is_red:    {result.is_red}')

        show_detection(frame, result)

        # To save the detection result image, remove the # from the line below.
        # save_detection_image(frame, result)

        # Robot: execute pick sequence using result.positions and result.is_red here.

        if len(result.positions) > 8:
            if not ask_operator(f'{len(result.positions)} modules detected. Continue?'):
                if not ask_operator('Run again?'):
                    break
                continue

        if not ask_operator('Run again with next battery?'):
            break

    camera.release()
    cv2.destroyAllWindows()
    print('--- System shut down ---')


if __name__ == '__main__':
    main()